### ISSUE TITLE
phpstan/phpstan

### ISSUE THREAD

**Issue by andreybolonin** [sstalle/php7cc#110] opened 2017-06-24 23:03 UTC
![screenshot from 2017-06-25 02-02-30](https://user-images.githubusercontent.com/2576509/27512488-673a0158-594a-11e7-896a-e156a1f2cbac.png)

What about to update nikic/php-parser to ^2.1 ?

**Comment by sstalle** [comment] 2017-06-25 19:30
I still don't have an ETA for that update unfortunately. I'm closing this issue as it's a duplicate of #79.

**Closed by sstalle** 2017-06-25 19:30 UTC
